### ISSUE TITLE
It is support time-serise Classification task?

### ISSUE THREAD

**Issue by CAI23sbP** [Maghoumi/pytorch-softdtw-cuda#34]
@Maghoumi  How are you?
Thank you for sharing your code.
In this[ paper,](https://arxiv.org/pdf/1703.01541) it showed that Soft-DTW is able to use classification task. your code is able to do it?

**Comment by Maghoumi** [comment]
Hi there!

Yes it should be able to do that because this repo is an implementation of the SDTW from the paper you linked.

In that paper under `3.3. Learning prototypes for time series classification`, they propose using the "nearest centroid classifier" instead of k-NN, and they are using SDTW in two different ways:

> Soft-DTW can naturally be used in a nearest centroid classifier, in order to **(1) compute the barycenter of each class at train time**, and to **(2) compute the discrepancy between barycenters and time series**, at prediction time.

**Comment by CAI23sbP** [comment]
Thank you for your replay!
