### ISSUE TITLE
Value for bandwitdh pruning?

### ISSUE THREAD

**Issue by hadaev8** [Maghoumi/pytorch-softdtw-cuda#4]
Should it be in the range 0-1 or 0-max_len?

**Comment by Maghoumi** [comment]
It's in the range 0 to max_len.

**Comment by hadaev8** [comment]
It would be nice to have bandwidth param per sample because in sequence tasks samples usually have different lengths.

**Comment by Maghoumi** [comment]
You can work around this by running sDTW on each pair of sequences separately. This will run slower obviously.

> because in sequence tasks samples usually have different lengths.

While that's true, the current implementation just doesn't support sequences of different lengths. What's needed is adding support for taking the length of each sequence as the input and computing sDTW while taking the length into consideration. Such implementation will likely be slow too. The main issue is that this kind of check would cause too much code path divergence in the CUDA kernel (due to `if` checks), which will surely slow down the execution.

I don't have any plans to add such support, but if you're interested in taking this on, I'd be happy to review the PR and merge.
